name: Release

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    env:
      CCACHE_MAXSIZE: "10G"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
      - name: Install NDK
        run: |
          echo "y" | sdkmanager --install "ndk;21.4.7075529" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
          echo "sdk.dir=${ANDROID_HOME}" >> local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/21.4.7075529" >> local.properties
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Chmod Gradle
        run: chmod +x gradlew
      - name: Build
        run: |
          export commit="${{ github.event.head_commit.message }}"
          export commit_author="${{ github.actor }}"
          export commit_sha="${{ github.sha }}"
          export run_num="${{ github.run_number }}"
          export CC="ccache gcc" 
          export CXX="ccache g++" 
          bash build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release APK
          path: ${{ github.workspace }}/TMessagesProj/build/outputs/apk
